### ISSUE TITLE
Only support mounting a single NetCDF file

### ISSUE THREAD

**Issue by blazk** [dvalters/fuse-netcdf#12]
Hello Declan,
Current version seems to support mounting a directory containing multiple netcdf files.
Would you consider simplifying the code by only supporting mounting a single NetCDF file?
The logic is a bit difficult to follow as the code needs to deal with both NetCDF files and regular files/directories, and this feature (mounting directories) doesn't seem to work correctly anyway.

I personally would remove these bits & keep it simple: if first argument is a netcdf file mount it, otherwise abort.

What do you think?

**Comment by dvalters** [comment]
Hi Blazej,

Yes I agree that would be much simpler - I have some more changes I'm working on today, I will incorporate this as well.

Declan

**Comment by dvalters** [comment]
Closed by PR #18
